---
# vars file for flatpak
flatpaks_apps:
  ### Internet / Communications
  - io.gitlab.librewolf-community
  - org.mozilla.Thunderbird
  - org.qbittorrent.qBittorrent
  ### Multimedia playsers
  - info.smplayer.SMPlayer
  - org.atheme.audacious
  - org.gnome.gThumb
  ### Gnome Tools
  - com.mattjakeman.ExtensionManager
  - com.github.tchx84.Flatseal
  ### Others
  - com.obsproject.Studio
  - org.standardnotes.standardnotes
  - com.vscodium.codium
  ### Non-free
  - com.valvesoftware.Steam
  - org.telegram.desktop
  - com.discordapp.Discord
