---
- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Remove installed aur packages
  become: true
  community.general.pacman:
    name:
      - yay
      - miniconda3
    state: absent

- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: Install conda
  kewlfft.aur.aur:
    name: miniconda3
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: Initialise Conda
  ansible.builtin.shell: 
    source /opt/miniconda3/etc/profile.d/conda.sh; conda init bash
