---
# tasks file for common

- name: Install GNOME
  become: true
  community.general.pacman:
    name: "{{ pacman_gnome_minimal }}"
    state: present
    update_cache: true

- name: Enable gdm
  become: true
  ansible.builtin.systemd:
    name: gdm
    enabled: yes
    masked: no
