---
# tasks file for common
- name: Synchronize Pacman packages
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install Packages
  become: true
  community.general.pacman:
    name:
      "{{ pacman_gnome_minimal
        + pacman_others
        + pacman_cups
        + pacman_collections }}"

- name: Enable gdm
  become: true
  ansible.builtin.systemd:
    name: gdm
    enabled: yes
    masked: no

- name: Enable CUPS
  become: true
  ansible.builtin.systemd:
    name: cups.socket
    enabled: yes
    masked: no

- name: Clone yay
  become: false
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "/tmp/ansible-yay-install"
    update: true

- name: Install yay
  become: false
  ansible.builtin.command:
    chdir: "/tmp/ansible-yay-install"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
