---
- name: Install Packages
  become: true
  community.general.pacman:
    name:
      "{{ pacman_cups
        + pacman_collections }}"
    state: latest
    update_cache: true

- name: Enable CUPS
  become: true
  ansible.builtin.systemd:
    name: cups.socket
    enabled: yes
    masked: no
